export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST"
export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS"
export const FETCH_PROJECTS_FAILURE = "FETCH_PROJECTS_FAILURE"

export const FETCH_PROJECT_DETAILS_REQUEST = "FETCH_PROJECT_DETAILS_REQUEST"
export const FETCH_PROJECT_DETAILS_SUCCESS = "FETCH_PROJECT_DETAILS_SUCCESS"
export const FETCH_PROJECT_DETAILS_FAILURE = "FETCH_PROJECT_DETAILS_FAILURE"