export const FETCH_MY_PROJECT_REQUEST = "FETCH_MY_PROJECT_REQUEST"
export const FETCH_MY_PROJECT_SUCCESS = "FETCH_MY_PROJECT_SUCCESS"
export const FETCH_MY_PROJECT_FAILURE = "FETCH_MY_PROJECT_FAILURE"

export const ADD_POST_PROJECT_REQUEST = "ADD_POST_PROJECT_REQUEST"
export const ADD_POST_PROJECT_SUCCESS = "ADD_POST_PROJECT_SUCCESS"
export const ADD_POST_PROJECT_FAILURE = "ADD_POST_PROJECT_FAILURE"